server:
  port: 8888

spring:
  profiles:
    active: native, jdbc
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          searchLocations: file://${user.home}/config-repo
        git:
          uri: https://github.com/mjspka/configserver.git/config-repo
        vault:
          port: 8200
          host: 127.0.01
        jdbc:
          sql: "SELECT PROPERTIES.PROP_KEY, PROPERTIES.VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
  datasource:
    url: "jdbc:h2:file:./data/demo"
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console: 
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
management:
  endpoints:
    web:
      exposure:
        include: info, health, env